# Generated by Django 5.1.7 on 2025-06-01 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('idBarrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreBarrio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Barrio',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(max_length=100)),
                ('anioFundacion', models.IntegerField()),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('cantBuses', models.IntegerField()),
                ('cantConductores', models.IntegerField()),
            ],
            options={
                'db_table': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('idTiempo', models.AutoField(primary_key=True, serialize=False)),
                ('diaSemana', models.CharField(max_length=20)),
                ('numeroSemana', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Tiempo',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TipoUsuario',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('horaSalida', models.TimeField()),
                ('horaLlegada', models.TimeField()),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.empresa')),
            ],
            options={
                'db_table': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('idRuta', models.AutoField(primary_key=True, serialize=False)),
                ('inicioRuta', models.CharField(max_length=100)),
                ('destinoRuta', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=50)),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.empresa')),
            ],
            options={
                'db_table': 'Ruta',
            },
        ),
        migrations.CreateModel(
            name='RutaBarrio',
            fields=[
                ('idRutaBarrio', models.AutoField(primary_key=True, serialize=False)),
                ('idBarrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.barrio')),
                ('idRuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.ruta')),
            ],
            options={
                'db_table': 'RutaBarrio',
            },
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('idDetalleRuta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadPasajeros', models.IntegerField()),
                ('idRuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.ruta')),
                ('idTiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.tiempo')),
            ],
            options={
                'db_table': 'DetalleRuta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('idTipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.tipousuario')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
