# Generated by Django 5.1.7 on 2025-06-02 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempo',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='diaSemana',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='mes',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='numeroSemana',
            field=models.IntegerField(editable=False),
        ),
    ]
