# Generated by Django 5.1.7 on 2025-06-03 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_tiempo_fecha_alter_tiempo_diasemana_alter_tiempo_mes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempo',
            name='diaSemana',
        ),
        migrations.RemoveField(
            model_name='tiempo',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='tiempo',
            name='numeroSemana',
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destinoRuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_destino', to='sistema.barrio'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='inicioRuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_inicio', to='sistema.barrio'),
        ),
    ]
