from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('usuario/dashboard/', views.usuario_dashboard, name='usuario_dashboard'),
    path('registrar/', views.registrar_usuario, name='registrar_usuario'),
    path('empresas/', views.lista_empresas, name='lista_empresas'),
    path('empresas/crear/', views.crear_empresa, name='crear_empresa'),
    path('empresas/editar/<int:id>/', views.editar_empresa, name='editar_empresa'),
    path('empresas/eliminar/<int:id>/', views.eliminar_empresa, name='eliminar_empresa'),
    path('admin/', views.admin_dashboard, name='admin_dashboard'),
    path('barrios/', views.lista_barrios, name='lista_barrios'),
    path('usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('registrar/', views.registrar_usuario, name='registrar_usuario'),
    path('horarios/', views.lista_horarios, name='lista_horarios'),
    path('horarios/crear/', views.crear_horario, name='crear_horario'),
    path('horarios/editar/<int:pk>/', views.editar_horario, name='editar_horario'),
    path('horarios/eliminar/<int:pk>/', views.eliminar_horario, name='eliminar_horario'),
    path('rutas/', views.lista_rutas, name='lista_rutas'),
    path('rutas/crear/', views.crear_ruta, name='crear_ruta'),
    path('rutas/editar/<int:pk>/', views.editar_ruta, name='editar_ruta'),
    path('rutas/eliminar/<int:pk>/', views.eliminar_ruta, name='eliminar_ruta'),
    path('tiempos/', views.listar_tiempos, name='listar_tiempos'),
    path('tiempos/crear/', views.crear_tiempo, name='crear_tiempo'),
    path('tiempos/editar/<int:id>/', views.editar_tiempo, name='editar_tiempo'),
    path('tiempos/eliminar/<int:id>/', views.eliminar_tiempo, name='eliminar_tiempo'),
    path('detalle_rutas/', views.lista_detalles_rutas, name='lista_detalles_rutas'),
    path('detalle_rutas/crear/', views.crear_detalle_ruta, name='crear_detalle_ruta'),
    path('detalle_rutas/editar/<int:pk>/', views.editar_detalle_ruta, name='editar_detalle_ruta'),
    path('detalle_rutas/eliminar/<int:pk>/', views.eliminar_detalle_ruta, name='eliminar_detalle_ruta'),
    path('barrios/', views.lista_barrios, name='lista_barrios'),
    path('barrios/crear/', views.crear_barrio, name='crear_barrio'),
    path('barrios/editar/<int:pk>/', views.editar_barrio, name='editar_barrio'),
    path('barrios/eliminar/<int:pk>/', views.eliminar_barrio, name='eliminar_barrio'),
    path('buscar-rutas/', views.buscar_rutas_por_barrio, name='buscar_rutas_por_barrio'),
    path('perfil/actualizar/', views.actualizar_cuenta, name='actualizar_cuenta'),
    path('perfil/eliminar/', views.eliminar_cuenta, name='eliminar_cuenta'),
    path('buscar-rutas/', views.buscar_rutas_ajax, name='buscar_rutas_ajax'),
    path('api/obtener-rutas/', views.buscar_rutas_por_barrio, name='obtener_rutas_por_barrio'),
    path('admin/estadisticas/', views.estadisticas_view, name='ver_estadisticas'),
    path('admin/reporte/', views.descargar_reporte_csv, name='descargar_reporte_csv'),

]